{"status": "broken", "description": "Obstacle placement for the navigation test.\n        ", "labels": [{"name": "tag", "value": "hypothesis"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "nav_test"}, {"name": "subSuite", "value": "TestNavigation"}, {"name": "host", "value": "Hyper-Dock"}, {"name": "thread", "value": "18416-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "tests.nav_test"}], "stop": 1606100835342, "uuid": "3635da32-606c-43a1-9c2f-8637abafc3de", "historyId": "09b3e2b6796b6a978f8f914c17f56fd7", "name": "test_obstacle_placement", "start": 1606100833653, "fullName": "tests.nav_test.TestNavigation#test_obstacle_placement", "statusDetails": {"message": "Flaky: Hypothesis test_obstacle_placement(self=<tests.nav_test.TestNavigation instance at 0x7f714c876b48>, obstacle='minicoffeetable') produces unreliable results: Falsified on the first call but did not on a subsequent one", "trace": "self = <tests.nav_test.TestNavigation instance at 0x7f714c876b48>\n\n    @settings(max_examples=1)\n>   @given(st.sampled_from(['minicoffeetable','coffeetable']))\n    def test_obstacle_placement(self,obstacle):\n        \"\"\"Obstacle placement for the navigation test.\n\ntests/nav_test.py:57: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/usr/local/lib/python2.7/dist-packages/hypothesis/core.py:656: in execute_once\n    % (test.__name__, text_repr[0])\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <hypothesis.core.StateForActualGivenExecution object at 0x7f7155a38b10>\nmessage = \"Hypothesis test_obstacle_placement(self=<tests.nav_test.TestNavigation instance at 0x7f714c876b48>, obstacle='minicoffeetable') produces unreliable results: Falsified on the first call but did not on a subsequent one\"\n\n    def __flaky(self, message):\n        if len(self.falsifying_examples) <= 1:\n>           raise Flaky(message)\nE           Flaky: Hypothesis test_obstacle_placement(self=<tests.nav_test.TestNavigation instance at 0x7f714c876b48>, obstacle='minicoffeetable') produces unreliable results: Falsified on the first call but did not on a subsequent one\n\n/usr/local/lib/python2.7/dist-packages/hypothesis/core.py:856: Flaky"}, "attachments": [{"source": "5e561b51-1362-4ebf-8ee9-98085b760756-attachment.txt", "type": "text/plain", "name": "log"}, {"source": "a181a7a0-cada-4e3e-878a-2bdcc3edf3ce-attachment.txt", "type": "text/plain", "name": "stdout"}, {"source": "3d5767b3-c645-45db-a1ad-cc8a35886fec-attachment.txt", "type": "text/plain", "name": "stderr"}]}